# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (0, 'unknown')], verbose_name='性別')),
                ('profession', models.CharField(max_length=128, verbose_name='職業')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ')),
                ('phone', models.CharField(max_length=128, verbose_name='電話')),
                ('status', models.IntegerField(choices=[(0, 'apply'), (1, 'pass'), (2, 'reject')], default=0, verbose_name='審核狀態')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '學員信息',
                'verbose_name_plural': '學員信息',
                'db_table': 'Student',
            },
        ),
    ]
