# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200518_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(auto_created=True, max_length=128, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
